# Cows and Bulls is a pen and paper code-breaking game usually played between 2 players. In this, a player tries to guess a secret code number chosen by the second player. The rules are as follows:
# 1) A player will create a secret code, usually a 4-digit number.  This number should have no repeated digits.
# 2) Another player makes a guess (4 digit number) to crack the secret number. Upon making a guess, 2 hints will be provided- Cows and Bulls.
# 3) Bulls indicate the number of correct digits in the correct position and cows indicates the number of correct digits in the wrong position. For example, if the secret code is 1234 and the guessed number is 1246 then we have 2 BULLS (for the exact matches of digits 1 and 2) and 1 COW (for the match of digit 4 in the wrong position)
# 4) The player keeps on guessing until the secret code is cracked.

import random
print("Welcome to cow bull game.\nIn this game you try to guess a serect code randomly generated by program.\nThe rules are following : \n1) Program will generate a serect 4 digit code with no repeated digits.\n2) you have to guess a 4 digit number to crack the secret number. Upon making a guess, 2 hints will be provided- Cows and Bulls.\n3) Bulls indicate the number of correct digits in the correct position and cows indicates the number of correct digits in the wrong position. For example, if the secret code is 1234 and the guessed number is 1246 then we have 2 BULLS (for the exact matches of digits 1 and 2) and 1 COW (for the match of digit 4 in the wrong position.\n4)You have to keep on guessing until the secret code is cracked.")
serect_code="".join(random.sample("0123456789", 4))
print(serect_code)
bull=0
cow=0
a=0
while True:
	guess=input("Guess the four digit serect code : ")
	for i in guess:
		if i not in serect_code:
			a+=1
		else:
			if int(i)==int(serect_code[a]):
				bull=bull+1
				a+=1
			else:
				cow+=1
				a+=1
	a=0
	print("Bulls : ",bull)
	print("Cows : ",cow)
	if bull==4:
		print("You guessed the right code.")
		break
	bull=0
	cow=0

